import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { join, relative, resolve } from "node:path";
import { appendAgentTrailer } from "../../commit-trailer.ts";
import { pushCurrent } from "../../worktree.ts";

export type CommitPlanInterviewOptions = {
  worktreePath: string;
  name: string;
  mode: "file" | "inline";
  intentPathOrLabel: string;
};

export function commitPlanInterview(opts: CommitPlanInterviewOptions): void {
  execFileSync("git", ["add", "-A"], {
    cwd: opts.worktreePath,
    stdio: "pipe",
  });

  let bodyLine: string;
  if (opts.mode === "file") {
    // Check if the path is within the project root
    const projectRoot = getProjectRoot(opts.worktreePath);
    const resolvedIntentPath = resolve(opts.intentPathOrLabel);
    const resolvedProjectRoot = resolve(projectRoot);
    const relativePath = relative(resolvedProjectRoot, resolvedIntentPath);

    if (relativePath.startsWith("..")) {
      // Path is outside project root, use basename only
      bodyLine = `Seeded from ${opts.intentPathOrLabel.split("/").pop()}`;
    } else {
      // Path is within project root, use relative path
      bodyLine = `Seeded from ${relativePath}`;
    }
  } else {
    bodyLine = `Seeded from inline`;
  }

  const subject = "plan: interview";
  const baseMessage = `${subject}\n\n${bodyLine}`;
  const commitMessage = appendAgentTrailer(baseMessage, "");

  execFileSync("git", ["commit", "-F", "-"], {
    cwd: opts.worktreePath,
    env: process.env,
    stdio: ["pipe", "pipe", "pipe"],
    input: commitMessage,
  });

  try {
    pushCurrent({ cwd: opts.worktreePath, firstPush: true });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(message);
  }
}

export type CommitPlanDraftOptions = {
  worktreePath: string;
  name: string;
};

export function commitPlanDraft(opts: CommitPlanDraftOptions): void {
  const specDir = join(opts.worktreePath, "spec", opts.name);

  // Create placeholder index.md
  const titleFromName = opts.name
    .split("-")
    .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
    .join(" ");
  const indexContent = `# ${titleFromName}\n\n- [ ] [00 - Placeholder task](./00-task.md)\n`;
  writeFileSync(join(specDir, "index.md"), indexContent, "utf8");

  // Create placeholder 00-task.md
  const taskContent = `# 00 - Placeholder task

This file is a placeholder produced by plan mode's worktree-and-commits
skeleton. Real spec content will be generated by the draft phase
introduced in \`spec/plan-mode-draft-and-review/\`.

## Acceptance criteria

- [ ] (placeholder)
`;
  writeFileSync(join(specDir, "00-task.md"), taskContent, "utf8");

  execFileSync("git", ["add", "-A"], {
    cwd: opts.worktreePath,
    stdio: "pipe",
  });

  const subject = "plan: draft";
  const body = `Placeholder draft. Real content comes from spec/plan-mode-draft-and-review/.
Subspecs: 1`;
  const baseMessage = `${subject}\n\n${body}`;
  const commitMessage = appendAgentTrailer(baseMessage, "");

  execFileSync("git", ["commit", "-F", "-"], {
    cwd: opts.worktreePath,
    env: process.env,
    stdio: ["pipe", "pipe", "pipe"],
    input: commitMessage,
  });

  try {
    pushCurrent({ cwd: opts.worktreePath, firstPush: false });
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(message);
  }
}

function getProjectRoot(cwd: string): string {
  try {
    return execFileSync("git", ["rev-parse", "--show-toplevel"], {
      cwd,
      encoding: "utf8",
      stdio: "pipe",
    }).trim();
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err);
    throw new Error(`could not find git root: ${message}`);
  }
}
